# Generated by Django 2.2.12 on 2021-03-25 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('gs_empid', models.AutoField(db_column='gs_empid', primary_key=True, serialize=False)),
                ('gs_empfirstname', models.CharField(db_column='gs_empfirstname', max_length=100)),
                ('gs_emplastname', models.CharField(db_column='gs_emplastname', max_length=100)),
                ('gs_empdob', models.DateTimeField(db_column='gs_empdob')),
                ('gs_gender', models.CharField(db_column='gs_gender', max_length=100)),
                ('gs_value', models.TextField(blank=True, db_column='gs_value')),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'EMPLOYE_RECORD',
            },
        ),
    ]
